// <auto-generated />
using System;
using Financeiro.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financeiro.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319205717_MigrateInicial")]
    partial class MigrateInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Financeiro.Api.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Financeiro.Api.Domain.Entities.DocumentoFinanceiro", b =>
                {
                    b.Property<int>("DocumentoFinanceiroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentoFinanceiroId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DocumentoFinanceiroId");

                    b.ToTable("DocumentoFinanceiro");

                    b.HasDiscriminator().HasValue("DocumentoFinanceiro");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Financeiro.Api.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("FornecedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FornecedorId"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("FornecedorId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("Financeiro.Api.Domain.Entities.Parcela", b =>
                {
                    b.Property<int>("ParcelaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ParcelaId"));

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime");

                    b.Property<int>("DocumentoFinanceiroId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ParcelaId");

                    b.HasIndex("DocumentoFinanceiroId");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("Financeiro.Api.Domain.Entities.ContaAPagar", b =>
                {
                    b.HasBaseType("Financeiro.Api.Domain.Entities.DocumentoFinanceiro");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroNota")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasIndex("FornecedorId");

                    b.HasDiscriminator().HasValue("ContaAPagar");
                });

            modelBuilder.Entity("Financeiro.Api.Domain.Entities.ContaAReceber", b =>
                {
                    b.HasBaseType("Financeiro.Api.Domain.Entities.DocumentoFinanceiro");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime");

                    b.HasIndex("ClienteId");

                    b.HasDiscriminator().HasValue("ContaAReceber");
                });

            modelBuilder.Entity("Financeiro.Api.Domain.Entities.Parcela", b =>
                {
                    b.HasOne("Financeiro.Api.Domain.Entities.DocumentoFinanceiro", "DocumentoFinanceiro")
                        .WithMany("Parcelas")
                        .HasForeignKey("DocumentoFinanceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoFinanceiro");
                });

            modelBuilder.Entity("Financeiro.Api.Domain.Entities.ContaAPagar", b =>
                {
                    b.HasOne("Financeiro.Api.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Financeiro.Api.Domain.Entities.ContaAReceber", b =>
                {
                    b.HasOne("Financeiro.Api.Domain.Entities.Cliente", "Cliente")
                        .WithMany("ContasAReceber")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Financeiro.Api.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ContasAReceber");
                });

            modelBuilder.Entity("Financeiro.Api.Domain.Entities.DocumentoFinanceiro", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
